/*
 * This source file was generated by the Gradle 'init' task
 */
package de.aldu.aoc;

public class Main {
    public static void main(String[] args) {
        // Day01.solve();
        // Day02.solve();
        Day03.solve();
    }
}
