/*
 * This source file was generated by the Gradle 'init' task
 */
package de.aldu.aoc;

import de.aldu.aoc.solutions.Day05;

public class Main {

  static void main(String[] args) {
    //  new Day01().executeTasks();
    //  new Day02().executeTasks();
    //  new Day03().executeTasks();
    // new Day04().executeTasks();
    new Day05().executeTasks();
  }

}