/*
 * This source file was generated by the Gradle 'init' task
 */
package de.aldu.aoc;

public class Main {

  static void main(String[] args) {
//    Day01.solve();
//    Day02.solve();
//    Day03.solve();
    Day04.solve();
  }
}
